class InstructorSubscriptionModel{
  late bool hasError;
  late List<dynamic> errors;
  late List<dynamic> messages;
  late Data? data;

  InstructorSubscriptionModel.formJson(Map<String,dynamic> json){
    hasError = json['hasError'];
    errors = json['errors'];
    messages = json['messages'];
    if(json['data'] is Map)
    {
      data = Data.fromJson(json['data']);
    }
    else
    {
      data = null;
    }
  }
}

class Data {
  String? resultsTotal;
  int? pageCurrent;
  dynamic pagePrev;
  dynamic pageNext;
  int? pageMax;
  List<ProductsSubscriptions>? productsSubscriptions;



  Data.fromJson(Map<String, dynamic> json) {
    resultsTotal = json['resultsTotal'];
    pageCurrent = json['pageCurrent'];
    pagePrev = json['pagePrev'];
    pageNext = json['pageNext'];
    pageMax = json['pageMax'];
    if (json['products_subscriptions'] != null) {
      productsSubscriptions = <ProductsSubscriptions>[];
      json['products_subscriptions'].forEach((v) {
        productsSubscriptions!.add(new ProductsSubscriptions.fromJson(v));
      });
    }
  }

}

class ProductsSubscriptions {
  String? pROSUBSCRIPTIONID;
  String? iNVID;
  String? iTEMID;
  String? pRODUCTID;
  String? sTUDENTID;
  String? iNSTRUCTORID;
  String? prosubscriptionTokens;
  String? prosubscriptionSessions;
  String? prosubscriptionSessionsRemaining;
  String? prosubscriptionStatus;
  String? prosubscriptionExpirable;
  String? prosubscriptionDateStart;
  String? prosubscriptionDateEnd;
  String? prosubscriptionNotes;
  String? prosubscriptionIdcardFilename;
  String? sTUDENTAFID;
  String? studentUniqueid;
  String? studentFullname;
  String? studentType;
  String? studentEmail;
  String? studentPhone;
  String? studentCertificateName;
  String? studentTaxesId;
  String? studentTradingId;
  String? studentSales;
  String? studentSalesReturns;
  String? studentSalesPaid;
  String? studentSalesWithdrawed;
  String? studentPurchases;
  String? studentPurchasesReturns;
  String? studentPurchasesPaid;
  String? studentPurchasesWithdrawed;
  String? studentDebit;
  String? studentCredit;
  String? studentBalance;
  String? studentDebitInitial;
  String? studentCreditInitial;
  String? studentBalanceInitial;
  String? studentUsername;
  String? studentPassword;
  String? studentGender;
  String? studentOrganization;
  String? studentDescription;
  String? studentCountry;
  String? studentOrders;
  String? studentAddTime;
  String? studentLoginTime;
  String? studentVerified;
  String? studentStatus;
  String? studentAssessed;
  String? studentAssessedNotes;
  String? studentForcePassword;
  String? studentProfilepicture;
  String? studentCoverpicture;
  String? studentWebsite;
  dynamic studentRememberMeKey;
  dynamic studentRememberMeTime;
  String? studentIp;
  String? studentLip;
  String? studentMylang;
  String? studentMycountry;
  String? studentFacebookConnected;
  String? studentFacebookId;
  String? studentVcode;
  String? studentVcodeTime;
  String? studentResetVcode;
  String? studentResetVcodeTime;
  String? studentGoogleConnected;
  String? studentGoogleId;
  String? studentCity;
  String? studentStreet;
  String? studentBuilding;
  String? studentPhone2;
  String? studentAddressInfo;
  String? studentCode;
  String? studentPoints;
  String? studentZoomConnected;
  String? studentZoomId;
  String? studentZoomEmail;
  String? studentZoomPersonalMeetingUrl;
  String? studentZoomJid;
  String? studentZoomAccountId;
  String? studentZoomAccessToken;
  String? studentZoomRefreshToken;
  String? studentWhatsappEnabled;
  String? studentWhatsappGroupName;
  String? studentWhatsappNumber;
  String? studentTimezone;
  String? studentIdcardFilename;
  String? studentAccesstoken;
  String? studentFirebaseAccesstoken;
  String? pRODUCTSCATID;
  String? pROPOSTID;
  String? productPn;
  String? productName;
  String? productActive;
  String? productNew;
  String? productSale;
  String? productType;
  String? productAssessment;
  String? productGroup;
  String? productTokens;
  String? productPrice;
  String? productOrderQty1;
  String? productOrderDiscount1;
  String? productOrderQty2;
  String? productOrderDiscount2;
  String? productOrderQty3;
  String? productOrderDiscount3;
  String? productSessions;
  String? productSessionsPriceMax;
  String? productSessionsPriceMin;
  String? productExamAuto;
  String? productExamId;
  String? productRestrictChapters;
  String? productSessionsMax;
  String? productDescription;
  String? productNotes;
  String? productReviewsTotal;
  String? productReviewsAvg;
  String? productTermFilename;
  String? productIntroFilename;
  String? productAdvantagesEnabled;
  String? productAdvantages;
  String? productGoalsEnabled;
  String? productGoals;
  String? productFormatEnabled;
  String? productFormat;
  String? productIdcardEnabled;
  String? productIdcardFilename;
  String? productIdcardDemoFilename;
  String? productIdcardNameX;
  String? productIdcardNameY;
  String? productIdcardNameColor;
  String? productIdcardNameFsize;
  String? productIdcardNameWidth;
  String? productIdcardBarcodeEnabled;
  String? productIdcardBarcodeX;
  String? productIdcardBarcodeY;
  String? productIdcardBarcodeWidth;
  String? productIdcardBarcodeHeight;
  String? productIdcardDateEnabled;
  String? productIdcardDateX;
  String? productIdcardDateY;
  String? productIdcardDateColor;
  String? productIdcardDateFsize;
  String? productCertificateEnabled;
  String? productCertificateFilename;
  String? productCertificateDemoFilename;
  String? productCertificateNameX;
  String? productCertificateNameY;
  String? productCertificateNameFsize;
  String? productCertificateNameColor;
  String? productCertificateNameWidth;
  String? productCertificateQrEnabled;
  String? productCertificateQrWidth;
  String? productCertificateQrX;
  String? productCertificateQrY;
  String? productCertificateDateEnabled;
  String? productCertificateDateX;
  String? productCertificateDateY;
  String? productCertificateDateColor;
  String? productCertificateInstructorEnabled;
  String? productCertificateInstructorX;
  String? productCertificateInstructorY;
  String? productCertificateInstructorFsize;
  String? productCertificateInstructorColor;
  String? productCertificateStudidEnabled;
  String? productCertificateStudidX;
  String? productCertificateStudidY;
  String? productCertificateStudidFsize;
  String? productCertificateStudidColor;
  String? status;



  ProductsSubscriptions.fromJson(Map<String, dynamic> json) {
    pROSUBSCRIPTIONID = json['PROSUBSCRIPTIONID'];
    iNVID = json['INVID'];
    iTEMID = json['ITEMID'];
    pRODUCTID = json['PRODUCTID'];
    sTUDENTID = json['STUDENTID'];
    iNSTRUCTORID = json['INSTRUCTORID'];
    prosubscriptionTokens = json['prosubscription_tokens'];
    prosubscriptionSessions = json['prosubscription_sessions'];
    prosubscriptionSessionsRemaining =
    json['prosubscription_sessions_remaining'];
    prosubscriptionStatus = json['prosubscription_status'];
    prosubscriptionExpirable = json['prosubscription_expirable'];
    prosubscriptionDateStart = json['prosubscription_date_start'];
    prosubscriptionDateEnd = json['prosubscription_date_end'];
    prosubscriptionNotes = json['prosubscription_notes'];
    prosubscriptionIdcardFilename = json['prosubscription_idcard_filename'];
    sTUDENTAFID = json['STUDENTAFID'];
    studentUniqueid = json['student_uniqueid'];
    studentFullname = json['student_fullname'];
    studentType = json['student_type'];
    studentEmail = json['student_email'];
    studentPhone = json['student_phone'];
    studentCertificateName = json['student_certificate_name'];
    studentTaxesId = json['student_taxes_id'];
    studentTradingId = json['student_trading_id'];
    studentSales = json['student_sales'];
    studentSalesReturns = json['student_sales_returns'];
    studentSalesPaid = json['student_sales_paid'];
    studentSalesWithdrawed = json['student_sales_withdrawed'];
    studentPurchases = json['student_purchases'];
    studentPurchasesReturns = json['student_purchases_returns'];
    studentPurchasesPaid = json['student_purchases_paid'];
    studentPurchasesWithdrawed = json['student_purchases_withdrawed'];
    studentDebit = json['student_debit'];
    studentCredit = json['student_credit'];
    studentBalance = json['student_balance'];
    studentDebitInitial = json['student_debit_initial'];
    studentCreditInitial = json['student_credit_initial'];
    studentBalanceInitial = json['student_balance_initial'];
    studentUsername = json['student_username'];
    studentPassword = json['student_password'];
    studentGender = json['student_gender'];
    studentOrganization = json['student_organization'];
    studentDescription = json['student_description'];
    studentCountry = json['student_country'];
    studentOrders = json['student_orders'];
    studentAddTime = json['student_add_time'];
    studentLoginTime = json['student_login_time'];
    studentVerified = json['student_verified'];
    studentStatus = json['student_status'];
    studentAssessed = json['student_assessed'];
    studentAssessedNotes = json['student_assessed_notes'];
    studentForcePassword = json['student_force_password'];
    studentProfilepicture = json['student_profilepicture'];
    studentCoverpicture = json['student_coverpicture'];
    studentWebsite = json['student_website'];
    studentRememberMeKey = json['student_remember_me_key'];
    studentRememberMeTime = json['student_remember_me_time'];
    studentIp = json['student_ip'];
    studentLip = json['student_lip'];
    studentMylang = json['student_mylang'];
    studentMycountry = json['student_mycountry'];
    studentFacebookConnected = json['student_facebook_connected'];
    studentFacebookId = json['student_facebook_id'];
    studentVcode = json['student_vcode'];
    studentVcodeTime = json['student_vcode_time'];
    studentResetVcode = json['student_reset_vcode'];
    studentResetVcodeTime = json['student_reset_vcode_time'];
    studentGoogleConnected = json['student_google_connected'];
    studentGoogleId = json['student_google_id'];
    studentCity = json['student_city'];
    studentStreet = json['student_street'];
    studentBuilding = json['student_building'];
    studentPhone2 = json['student_phone_2'];
    studentAddressInfo = json['student_address_info'];
    studentCode = json['student_code'];
    studentPoints = json['student_points'];
    studentZoomConnected = json['student_zoom_connected'];
    studentZoomId = json['student_zoom_id'];
    studentZoomEmail = json['student_zoom_email'];
    studentZoomPersonalMeetingUrl = json['student_zoom_personal_meeting_url'];
    studentZoomJid = json['student_zoom_jid'];
    studentZoomAccountId = json['student_zoom_account_id'];
    studentZoomAccessToken = json['student_zoom_access_token'];
    studentZoomRefreshToken = json['student_zoom_refresh_token'];
    studentWhatsappEnabled = json['student_whatsapp_enabled'];
    studentWhatsappGroupName = json['student_whatsapp_group_name'];
    studentWhatsappNumber = json['student_whatsapp_number'];
    studentTimezone = json['student_timezone'];
    studentIdcardFilename = json['student_idcard_filename'];
    studentAccesstoken = json['student_accesstoken'];
    studentFirebaseAccesstoken = json['student_firebase_accesstoken'];
    pRODUCTSCATID = json['PRODUCTSCATID'];
    pROPOSTID = json['PROPOSTID'];
    productPn = json['product_pn'];
    productName = json['product_name'];
    productActive = json['product_active'];
    productNew = json['product_new'];
    productSale = json['product_sale'];
    productType = json['product_type'];
    productAssessment = json['product_assessment'];
    productGroup = json['product_group'];
    productTokens = json['product_tokens'];
    productPrice = json['product_price'];
    productOrderQty1 = json['product_order_qty_1'];
    productOrderDiscount1 = json['product_order_discount_1'];
    productOrderQty2 = json['product_order_qty_2'];
    productOrderDiscount2 = json['product_order_discount_2'];
    productOrderQty3 = json['product_order_qty_3'];
    productOrderDiscount3 = json['product_order_discount_3'];
    productSessions = json['product_sessions'];
    productSessionsPriceMax = json['product_sessions_price_max'];
    productSessionsPriceMin = json['product_sessions_price_min'];
    productExamAuto = json['product_exam_auto'];
    productExamId = json['product_exam_id'];
    productRestrictChapters = json['product_restrict_chapters'];
    productSessionsMax = json['product_sessions_max'];
    productDescription = json['product_description'];
    productNotes = json['product_notes'];
    productReviewsTotal = json['product_reviews_total'];
    productReviewsAvg = json['product_reviews_avg'];
    productTermFilename = json['product_term_filename'];
    productIntroFilename = json['product_intro_filename'];
    productAdvantagesEnabled = json['product_advantages_enabled'];
    productAdvantages = json['product_advantages'];
    productGoalsEnabled = json['product_goals_enabled'];
    productGoals = json['product_goals'];
    productFormatEnabled = json['product_format_enabled'];
    productFormat = json['product_format'];
    productIdcardEnabled = json['product_idcard_enabled'];
    productIdcardFilename = json['product_idcard_filename'];
    productIdcardDemoFilename = json['product_idcard_demo_filename'];
    productIdcardNameX = json['product_idcard_name_x'];
    productIdcardNameY = json['product_idcard_name_y'];
    productIdcardNameColor = json['product_idcard_name_color'];
    productIdcardNameFsize = json['product_idcard_name_fsize'];
    productIdcardNameWidth = json['product_idcard_name_width'];
    productIdcardBarcodeEnabled = json['product_idcard_barcode_enabled'];
    productIdcardBarcodeX = json['product_idcard_barcode_x'];
    productIdcardBarcodeY = json['product_idcard_barcode_y'];
    productIdcardBarcodeWidth = json['product_idcard_barcode_width'];
    productIdcardBarcodeHeight = json['product_idcard_barcode_height'];
    productIdcardDateEnabled = json['product_idcard_date_enabled'];
    productIdcardDateX = json['product_idcard_date_x'];
    productIdcardDateY = json['product_idcard_date_y'];
    productIdcardDateColor = json['product_idcard_date_color'];
    productIdcardDateFsize = json['product_idcard_date_fsize'];
    productCertificateEnabled = json['product_certificate_enabled'];
    productCertificateFilename = json['product_certificate_filename'];
    productCertificateDemoFilename = json['product_certificate_demo_filename'];
    productCertificateNameX = json['product_certificate_name_x'];
    productCertificateNameY = json['product_certificate_name_y'];
    productCertificateNameFsize = json['product_certificate_name_fsize'];
    productCertificateNameColor = json['product_certificate_name_color'];
    productCertificateNameWidth = json['product_certificate_name_width'];
    productCertificateQrEnabled = json['product_certificate_qr_enabled'];
    productCertificateQrWidth = json['product_certificate_qr_width'];
    productCertificateQrX = json['product_certificate_qr_x'];
    productCertificateQrY = json['product_certificate_qr_y'];
    productCertificateDateEnabled = json['product_certificate_date_enabled'];
    productCertificateDateX = json['product_certificate_date_x'];
    productCertificateDateY = json['product_certificate_date_y'];
    productCertificateDateColor = json['product_certificate_date_color'];
    productCertificateInstructorEnabled =
    json['product_certificate_instructor_enabled'];
    productCertificateInstructorX = json['product_certificate_instructor_x'];
    productCertificateInstructorY = json['product_certificate_instructor_y'];
    productCertificateInstructorFsize =
    json['product_certificate_instructor_fsize'];
    productCertificateInstructorColor =
    json['product_certificate_instructor_color'];
    productCertificateStudidEnabled =
    json['product_certificate_studid_enabled'];
    productCertificateStudidX = json['product_certificate_studid_x'];
    productCertificateStudidY = json['product_certificate_studid_y'];
    productCertificateStudidFsize = json['product_certificate_studid_fsize'];
    productCertificateStudidColor = json['product_certificate_studid_color'];
    status = json['status'];
  }


}
